environments:
  default:
    values:
      - "../../environments/default/*.yaml*"
  demo:
    values:
      - "../../environments/default/*.yaml*"
      - "../../environments/demo/*.yaml.gotmpl"
  production:
    values:
      - "../../environments/default/*.yaml*"
      - "../../environments/production/*.yaml.gotmpl"
