{{- /*

SPDX-License-Identifier: APACHE-2.0
*/}}

{{- include "calendars.deployment" (dict
  "name"      "worker"
  "values"    .Values.worker
  "envValues" .Values.backend
  "hasHPA"    true
  "hasPorts"  false
  "probeType" ""
  "ctx"       $) }}
