{{- /*

SPDX-License-Identifier: APACHE-2.0
*/}}

apiVersion: {{ include "common.capabilities.deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: {{ template "common.names.fullname" . }}-caldav
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: calendars-caldav
  {{- if or .Values.caldav.deploymentAnnotations .Values.commonAnnotations }}
  {{- $annotations := include "common.tplvalues.merge" (dict "values" (list .Values.caldav.deploymentAnnotations .Values.commonAnnotations) "context" .) }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" $annotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.caldav.replicaCount }}
  {{- $podLabels := include "common.tplvalues.merge" (dict "values" (list .Values.caldav.podLabels .Values.commonLabels) "context" .) }}
  selector:
    matchLabels: {{- include "common.labels.matchLabels" ( dict "customLabels" $podLabels "context" $ ) | nindent 6 }}
      app.kubernetes.io/component: calendars-caldav
  template:
    metadata:
      {{- if .Values.caldav.podAnnotations }}
      annotations: {{- include "common.tplvalues.render" (dict "value" .Values.caldav.podAnnotations "context" $) | nindent 8 }}
      {{- end }}
      labels: {{- include "common.labels.standard" ( dict "customLabels" $podLabels "context" $ ) | nindent 8 }}
        app.kubernetes.io/component: calendars-caldav
    spec:
      {{- include "calendars.imagePullSecrets" . | nindent 6 }}
      serviceAccountName: {{ template "calendars.serviceAccountName" . }}
      automountServiceAccountToken: {{ .Values.caldav.automountServiceAccountToken }}
      {{- if .Values.caldav.hostAliases }}
      hostAliases: {{- include "common.tplvalues.render" (dict "value" .Values.caldav.hostAliases "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.caldav.affinity }}
      affinity: {{- include "common.tplvalues.render" ( dict "value" .Values.caldav.affinity "context" $) | nindent 8 }}
      {{- else }}
      affinity:
        podAffinity: {{- include "common.affinities.pods" (dict "type" .Values.caldav.podAffinityPreset "component" "calendars-caldav" "customLabels" $podLabels "context" $) | nindent 10 }}
        podAntiAffinity: {{- include "common.affinities.pods" (dict "type" .Values.caldav.podAntiAffinityPreset "component" "calendars-caldav" "customLabels" $podLabels "context" $) | nindent 10 }}
        nodeAffinity: {{- include "common.affinities.nodes" (dict "type" .Values.caldav.nodeAffinityPreset.type "key" .Values.caldav.nodeAffinityPreset.key "values" .Values.caldav.nodeAffinityPreset.values) | nindent 10 }}
      {{- end }}
      {{- if .Values.caldav.nodeSelector }}
      nodeSelector: {{- include "common.tplvalues.render" ( dict "value" .Values.caldav.nodeSelector "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.caldav.tolerations }}
      tolerations: {{- include "common.tplvalues.render" (dict "value" .Values.caldav.tolerations "context" .) | nindent 8 }}
      {{- end }}
      {{- if .Values.caldav.priorityClassName }}
      priorityClassName: {{ .Values.caldav.priorityClassName | quote }}
      {{- end }}
      {{- if .Values.caldav.schedulerName }}
      schedulerName: {{ .Values.caldav.schedulerName | quote }}
      {{- end }}
      {{- if .Values.caldav.runtimeClassName }}
      runtimeClassName: {{ .Values.caldav.runtimeClassName | quote }}
      {{- end }}
      {{- if .Values.caldav.topologySpreadConstraints }}
      topologySpreadConstraints: {{- include "common.tplvalues.render" (dict "value" .Values.caldav.topologySpreadConstraints "context" .) | nindent 8 }}
      {{- end }}
      {{- if .Values.caldav.podSecurityContext.enabled }}
      securityContext: {{- omit .Values.caldav.podSecurityContext "enabled" | toYaml | nindent 8 }}
      {{- end }}
      {{- if .Values.caldav.terminationGracePeriodSeconds }}
      terminationGracePeriodSeconds: {{ .Values.caldav.terminationGracePeriodSeconds }}
      {{- end }}
      {{- if .Values.caldav.initContainers }}
      initContainers:
        {{- include "common.tplvalues.render" (dict "value" .Values.caldav.initContainers "context" $) | nindent 8 }}
      {{- end }}
      containers:
        - name: calendars-caldav
          image: {{ template "calendars.caldav.image" . }}
          imagePullPolicy: {{ .Values.caldav.image.pullPolicy }}
          {{- if .Values.caldav.containerSecurityContext.enabled }}
          securityContext: {{- include "common.compatibility.renderSecurityContext" (dict "secContext" .Values.caldav.containerSecurityContext "context" $) | nindent 12 }}
          {{- end }}
          {{- if .Values.diagnosticMode.enabled }}
          command: {{- include "common.tplvalues.render" (dict "value" .Values.diagnosticMode.command "context" $) | nindent 12 }}
          {{- else if .Values.caldav.command }}
          command: {{- include "common.tplvalues.render" (dict "value" .Values.caldav.command "context" $) | nindent 12 }}
          {{- end }}
          {{- if .Values.diagnosticMode.enabled }}
          args: {{- include "common.tplvalues.render" (dict "value" .Values.diagnosticMode.args "context" $) | nindent 12 }}
          {{- else if .Values.caldav.args }}
          args: {{- include "common.tplvalues.render" (dict "value" .Values.caldav.args "context" $) | nindent 12 }}
          {{- end }}
          env:
            {{- range $key, $value := .Values.caldav.envVars }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            {{- if .Values.caldav.extraEnvVars }}
            {{- include "common.tplvalues.render" (dict "value" .Values.caldav.extraEnvVars "context" $) | nindent 12 }}
            {{- end }}
          {{- if or .Values.caldav.extraEnvVarsCM .Values.caldav.extraEnvVarsSecret }}
          envFrom:
            {{- if .Values.caldav.extraEnvVarsCM }}
            - configMapRef:
                name: {{ include "common.tplvalues.render" (dict "value" .Values.caldav.extraEnvVarsCM "context" $) }}
            {{- end }}
            {{- if .Values.caldav.extraEnvVarsSecret }}
            - secretRef:
                name: {{ include "common.tplvalues.render" (dict "value" .Values.caldav.extraEnvVarsSecret "context" $) }}
            {{- end }}
          {{- end }}
          {{- if .Values.caldav.resources }}
          resources: {{- toYaml .Values.caldav.resources | nindent 12 }}
          {{- else if ne .Values.caldav.resourcesPreset "none" }}
          resources: {{- include "common.resources.preset" (dict "type" .Values.caldav.resourcesPreset) | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.caldav.containerPorts.http }}
          {{- if not .Values.diagnosticMode.enabled }}
          {{- if .Values.caldav.livenessProbe.enabled }}
          livenessProbe: {{- include "common.tplvalues.render" (dict "value" (omit .Values.caldav.livenessProbe "enabled") "context" $) | nindent 12 }}
            tcpSocket:
              port: {{ .Values.caldav.containerPorts.http }}
          {{- end }}
          {{- if .Values.caldav.readinessProbe.enabled }}
          readinessProbe: {{- include "common.tplvalues.render" (dict "value" (omit .Values.caldav.readinessProbe "enabled") "context" $) | nindent 12 }}
            tcpSocket:
              port: {{ .Values.caldav.containerPorts.http }}
          {{- end }}
          {{- if .Values.caldav.startupProbe.enabled }}
          startupProbe: {{- include "common.tplvalues.render" (dict "value" (omit .Values.caldav.startupProbe "enabled") "context" $) | nindent 12 }}
            tcpSocket:
              port: {{ .Values.caldav.containerPorts.http }}
          {{- end }}
          {{- end }}
          {{- if .Values.caldav.lifecycleHooks }}
          lifecycle: {{- include "common.tplvalues.render" (dict "value" .Values.caldav.lifecycleHooks "context" $) | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: tmp
              mountPath: /tmp
            {{- if .Values.caldav.extraVolumeMounts }}
            {{- include "common.tplvalues.render" (dict "value" .Values.caldav.extraVolumeMounts "context" $) | nindent 12 }}
            {{- end }}
        {{- if .Values.caldav.sidecars }}
        {{- include "common.tplvalues.render" ( dict "value" .Values.caldav.sidecars "context" $) | nindent 8 }}
        {{- end }}
      volumes:
        - name: tmp
          emptyDir: {}
        {{- if .Values.caldav.extraVolumes }}
        {{- include "common.tplvalues.render" (dict "value" .Values.caldav.extraVolumes "context" $) | nindent 8 }}
        {{- end }}
