{{- /*

SPDX-License-Identifier: APACHE-2.0
*/}}

{{- include "calendars.deployment" (dict
  "name"      "caldav"
  "values"    .Values.caldav
  "hasHPA"    false
  "hasPorts"  true
  "probeType" "tcpSocket"
  "ctx"       $) }}
