{{- /*

SPDX-License-Identifier: APACHE-2.0
*/}}

{{- if .Values.networkPolicy.enabled }}
{{- include "calendars.networkpolicy" (dict
  "name"      "backend"
  "values"    .Values.backend
  "hasIngress" true
  "ctx"       $) }}
{{- include "calendars.networkpolicy" (dict
  "name"        "frontend"
  "values"      .Values.frontend
  "hasIngress"  true
  "backendEgress" true
  "ctx"         $) }}
{{- include "calendars.networkpolicy" (dict
  "name"      "worker"
  "values"    .Values.worker
  "hasIngress" false
  "ctx"       $) }}
{{- include "calendars.networkpolicy" (dict
  "name"      "caldav"
  "values"    .Values.caldav
  "hasIngress" true
  "ctx"       $) }}
{{- end }}
