{{- /*

SPDX-License-Identifier: APACHE-2.0
*/}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "common.names.fullname" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: find
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
  DJANGO_CONFIGURATION: Production
  DJANGO_SETTINGS_MODULE: find.settings
  DJANGO_ALLOWED_HOSTS: {{ .Values.find.AllowedHosts | quote }}
  DJANGO_CSRF_TRUSTED_ORIGINS: {{ .Values.find.CSRFTrustedOrigins | quote }}
  DB_HOST: {{ .Values.externalDatabase.host | quote }}
  DB_PORT: {{ .Values.externalDatabase.port | quote }}
  DB_NAME: {{ .Values.externalDatabase.database | quote }}
  DB_USER: {{ .Values.externalDatabase.username | quote }}
  OPENSEARCH_HOST: {{ .Values.externalOpenSearch.host | quote }}
  OPENSEARCH_PORT: {{ .Values.externalOpenSearch.port | quote }}
  OPENSEARCH_USER: "admin"
  OPENSEARCH_USE_SSL: {{ .Values.externalOpenSearch.useSSL | quote }}
  OPENSEARCH_VERIFY_CERTS: {{ .Values.externalOpenSearch.verifyCerts | quote }}
  STORAGES_STATICFILES_BACKEND: "django.contrib.staticfiles.storage.StaticFilesStorage"
  OIDC_OP_URL: {{ .Values.authentication.issuer | quote }}
  OIDC_OP_AUTHORIZATION_ENDPOINT: {{ .Values.authentication.authorization_endpoint | quote }}
  OIDC_OP_INTROSPECTION_ENDPOINT: {{ .Values.authentication.introspection_endpoint | quote }}
  OIDC_OP_LOGOUT_ENDPOINT: {{ .Values.authentication.end_session_endpoint | quote }}
  OIDC_OP_JWKS_ENDPOINT: {{ .Values.authentication.jwks_uri | quote }}
  OIDC_OP_TOKEN_ENDPOINT: {{ .Values.authentication.token_endpoint | quote }}
  OIDC_OP_USER_ENDPOINT: {{ .Values.authentication.userinfo_endpoint | quote }}
  OIDC_RP_CLIENT_ID: {{ .Values.authentication.client.client_id | quote }}
  OIDC_RS_CLIENT_ID: {{ .Values.authentication.client.client_id | quote }}
  OIDC_RS_INTROSPECTION_ENDPOINT: {{ .Values.authentication.introspection_endpoint | quote }}
  LOGIN_REDIRECT_URL: "https://{{ .Values.ingress.hostname }}"
  LOGIN_REDIRECT_URL_FAILURE: "https://{{ .Values.ingress.hostname }}"
  LOGOUT_REDIRECT_URL: "https://{{ .Values.ingress.hostname }}"
