{{- /*

SPDX-License-Identifier: APACHE-2.0
*/}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ template "common.names.fullname" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: find
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  DJANGO_SUPERUSER_EMAIL: {{ .Values.find.superuserEmail }}
  DJANGO_SUPERUSER_PASSWORD: {{ .Values.find.superuserPassword }}
  DJANGO_SECRET_KEY: {{ .Values.find.secretKey | quote }}
  DB_PASSWORD: {{ .Values.externalDatabase.password | quote }}
  REDIS_URL: "redis://default:{{ .Values.externalRedis.password }}@{{ .Values.externalRedis.host }}:{{ .Values.externalRedis.port }}/0"
  DJANGO_CELERY_BROKER_URL: "redis://default:{{ .Values.externalRedis.password }}@{{ .Values.externalRedis.host }}:{{ .Values.externalRedis.port }}/0"
  OPENSEARCH_PASSWORD: {{ .Values.externalOpenSearch.password | quote }}
  OIDC_RP_CLIENT_SECRET: {{ .Values.authentication.client.client_secret | quote }}
  OIDC_RS_CLIENT_SECRET: {{ .Values.authentication.client.client_secret | quote }}
  {{- if .Values.find.findServiceTokenDocs }}
  FIND_SERVICE_TOKEN_DOCS: {{ .Values.find.findServiceTokenDocs | quote }}
  {{- end }}
  {{- if .Values.find.findServiceTokenDrive }}
  FIND_SERVICE_TOKEN_DRIVE: {{ .Values.find.findServiceTokenDrive | quote }}
  {{- end }}
