## @section Global parameters
global:
  imageRegistry: ""
  imagePullSecrets: []
  defaultStorageClass: ""
  security:
    allowInsecureImages: false

## @param commonLabels Labels to add to all deployed objects
commonLabels: {}
## @param commonAnnotations Annotations to add to all deployed objects
commonAnnotations: {}

## @param clusterDomain Kubernetes cluster domain
clusterDomain: cluster.local

## @section Cluster routing configuration
cluster:
  routingMode: ingress
  ingress:
    type: nginx
    className: nginx
    annotations: {}
  runtimeClassName: ""

## @section Diagnostics
diagnosticMode:
  enabled: false
  command:
    - sleep
  args:
    - infinity

## @section Service account
serviceAccount:
  create: true
  name: ""
  annotations: {}
  automountServiceAccountToken: false

## @section Network policy
networkPolicy:
  enabled: true
  allowExternal: true
  allowExternalEgress: false
  extraIngress: []
  extraEgress: []
  ingressNSMatchLabels: {}
  ingressNSPodMatchLabels: {}

## @section Service
service:
  type: ClusterIP
  ports:
    http: 80
  nodePorts:
    http: ""
  clusterIP: ""
  sessionAffinity: None
  sessionAffinityConfig: {}
  annotations: {}

## @section Ingress
ingress:
  enabled: true
  hostname: calendars.kubernetes.local
  ingressClassName: nginx
  pathType: Prefix
  annotations: {}
  tls: true
  selfSigned: false
  extraTls: []

## @section Frontend configuration
frontend:
  image:
    registry: ghcr.io
    repository: suitenumerique/calendars-frontend
    tag: "sha256-618868febfad0229713edd246c1f82c44de075f1af0d88052afa700ad2e54310"
    pullPolicy: Always
    pullSecrets: []
    debug: false
  replicaCount: 1
  containerPorts:
    http: 8080
  resourcesPreset: small
  resources: {}
  podSecurityContext:
    enabled: true
    fsGroup: 1001
    fsGroupChangePolicy: Always
    sysctls: []
    supplementalGroups: []
  containerSecurityContext:
    enabled: true
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - "ALL"
    privileged: false
    runAsUser: 1001
    runAsGroup: 1001
    readOnlyRootFilesystem: true
    runAsNonRoot: true
  runtimeClassName: ""
  pdb:
    create: true
    maxUnavailable: 1
  autoscaling:
    hpa:
      enabled: false
      minReplicas: 1
      maxReplicas: 3
      targetCPU: 80
      targetMemory: ""
  podLabels: {}
  podAnnotations: {}
  podAffinityPreset: ""
  podAntiAffinityPreset: soft
  nodeAffinityPreset:
    type: ""
    key: ""
    values: []
  affinity: {}
  nodeSelector: {}
  tolerations: []
  priorityClassName: ""
  schedulerName: ""
  terminationGracePeriodSeconds: ""
  topologySpreadConstraints: []
  command: []
  args: []
  extraEnvVars: []
  extraEnvVarsCM: ""
  extraEnvVarsSecret: ""
  lifecycleHooks: {}
  livenessProbe:
    enabled: true
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1
  readinessProbe:
    enabled: true
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1
  startupProbe:
    enabled: false
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 15
    successThreshold: 1
  sidecars: []
  initContainers: []
  extraVolumeMounts: []
  extraVolumes: []
  automountServiceAccountToken: false
  hostAliases: []
  envVars: {}

## @section Backend configuration
backend:
  image:
    registry: ghcr.io
    repository: suitenumerique/calendars-backend
    tag: "sha256-f36350c7d4bd9bcb43110f1a93553bea4750ae63191fefa195217980d4c0aa44"
    pullPolicy: Always
    pullSecrets: []
    debug: false
  replicaCount: 1
  containerPorts:
    http: 8000
  resourcesPreset: small
  resources: {}
  podSecurityContext:
    enabled: true
    fsGroup: 1001
    fsGroupChangePolicy: Always
    sysctls: []
    supplementalGroups: []
  containerSecurityContext:
    enabled: true
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - "ALL"
    privileged: false
    runAsUser: 1001
    runAsGroup: 1001
    readOnlyRootFilesystem: true
    runAsNonRoot: true
  runtimeClassName: ""
  pdb:
    create: true
    maxUnavailable: 1
  autoscaling:
    hpa:
      enabled: false
      minReplicas: 1
      maxReplicas: 3
      targetCPU: 80
      targetMemory: ""
  networkPolicy:
    extraEgress: []
  podLabels: {}
  podAnnotations: {}
  podAffinityPreset: ""
  podAntiAffinityPreset: soft
  nodeAffinityPreset:
    type: ""
    key: ""
    values: []
  affinity: {}
  nodeSelector: {}
  tolerations: []
  priorityClassName: ""
  schedulerName: ""
  terminationGracePeriodSeconds: ""
  topologySpreadConstraints: []
  command: []
  args: []
  extraEnvVars: []
  extraEnvVarsCM: ""
  extraEnvVarsSecret: ""
  lifecycleHooks: {}
  livenessProbe:
    enabled: true
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1
  readinessProbe:
    enabled: true
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1
  startupProbe:
    enabled: false
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 15
    successThreshold: 1
  sidecars: []
  initContainers: []
  extraVolumeMounts: []
  extraVolumes: []
  automountServiceAccountToken: false
  hostAliases: []
  envVars: {}

## @section Worker configuration (Dramatiq)
worker:
  image:
    registry: ghcr.io
    repository: suitenumerique/calendars-backend
    tag: "sha256-f36350c7d4bd9bcb43110f1a93553bea4750ae63191fefa195217980d4c0aa44"
    pullPolicy: Always
    pullSecrets: []
    debug: false
  replicaCount: 1
  command:
    - python
    - manage.py
    - rundramatiq
  resourcesPreset: small
  resources: {}
  podSecurityContext:
    enabled: true
    fsGroup: 1001
    fsGroupChangePolicy: Always
    sysctls: []
    supplementalGroups: []
  containerSecurityContext:
    enabled: true
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - "ALL"
    privileged: false
    runAsUser: 1001
    runAsGroup: 1001
    readOnlyRootFilesystem: true
    runAsNonRoot: true
  runtimeClassName: ""
  pdb:
    create: true
    maxUnavailable: 1
  autoscaling:
    hpa:
      enabled: false
      minReplicas: 1
      maxReplicas: 3
      targetCPU: 80
      targetMemory: ""
  networkPolicy:
    extraEgress: []
  podLabels: {}
  podAnnotations: {}
  podAffinityPreset: ""
  podAntiAffinityPreset: soft
  nodeAffinityPreset:
    type: ""
    key: ""
    values: []
  affinity: {}
  nodeSelector: {}
  tolerations: []
  priorityClassName: ""
  schedulerName: ""
  terminationGracePeriodSeconds: ""
  topologySpreadConstraints: []
  args: []
  extraEnvVars: []
  extraEnvVarsCM: ""
  extraEnvVarsSecret: ""
  lifecycleHooks: {}
  sidecars: []
  initContainers: []
  extraVolumeMounts: []
  extraVolumes: []
  automountServiceAccountToken: false
  hostAliases: []

## @section CalDAV configuration (SabreDAV PHP/Apache)
caldav:
  image:
    registry: ghcr.io
    repository: suitenumerique/calendars-caldav
    tag: "sha256-ba5447053c2d65f3c4de0ceefded3638b71da93e7a5a91584e79fa3399822c40"
    pullPolicy: Always
    pullSecrets: []
    debug: false
  replicaCount: 1
  containerPorts:
    http: 8080
  resourcesPreset: small
  resources: {}
  podSecurityContext:
    enabled: true
    fsGroup: 33
    fsGroupChangePolicy: Always
    sysctls: []
    supplementalGroups: []
  containerSecurityContext:
    enabled: true
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - "ALL"
    privileged: false
    runAsUser: 33
    runAsGroup: 33
    readOnlyRootFilesystem: false
    runAsNonRoot: true
  runtimeClassName: ""
  networkPolicy:
    extraEgress: []
  podLabels: {}
  podAnnotations: {}
  podAffinityPreset: ""
  podAntiAffinityPreset: soft
  nodeAffinityPreset:
    type: ""
    key: ""
    values: []
  affinity: {}
  nodeSelector: {}
  tolerations: []
  priorityClassName: ""
  schedulerName: ""
  terminationGracePeriodSeconds: ""
  topologySpreadConstraints: []
  command: []
  args: []
  extraEnvVars: []
  extraEnvVarsCM: ""
  extraEnvVarsSecret: ""
  lifecycleHooks: {}
  livenessProbe:
    enabled: true
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1
  readinessProbe:
    enabled: true
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1
  startupProbe:
    enabled: false
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 15
    successThreshold: 1
  sidecars: []
  initContainers: []
  extraVolumeMounts: []
  extraVolumes: []
  automountServiceAccountToken: false
  hostAliases: []
  envVars: {}
